### ISSUE TITLE
رصيد سوا

### ISSUE THREAD

**Issue by Alfadlmwsymwsy** [MicrosoftDocs/OfficeDocs-DeployOffice#1258]
```[tasklist]
### Tasks
- [x] رصيد سوا
- [ ] https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/pull/1245
- [ ] https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/1242
- [ ] https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/1254
```

**Comment by Alfadlmwsymwsy** [comment]
Alfadlmwsymwsy803@gmail.com

**Comment by Alfadlmwsymwsy** [comment]
0504877382
